INFO 2025-06-24 22:46:16,078 autoreload 57428 50804 Watching for file changes with StatReloader
INFO 2025-06-24 22:58:01,304 autoreload 58296 59124 Watching for file changes with StatReloader
WARNING 2025-06-24 22:58:02,627 log 58296 50056 Not Found: /
WARNING 2025-06-24 22:58:02,628 basehttp 58296 50056 "GET / HTTP/1.1" 404 2308
WARNING 2025-06-24 22:58:06,776 log 58296 50056 Not Found: /mailing/
WARNING 2025-06-24 22:58:06,776 basehttp 58296 50056 "GET /mailing/ HTTP/1.1" 404 7300
INFO 2025-06-24 22:58:11,445 basehttp 58296 50056 "GET /mailing/recipients/ HTTP/1.1" 302 0
WARNING 2025-06-24 22:58:11,451 log 58296 50056 Not Found: /accounts/login/
WARNING 2025-06-24 22:58:11,452 basehttp 58296 50056 "GET /accounts/login/?next=/mailing/recipients/ HTTP/1.1" 404 2397
INFO 2025-06-24 23:00:12,312 autoreload 46400 62268 Watching for file changes with StatReloader
WARNING 2025-06-24 23:00:23,883 log 46400 59216 Not Found: /accounts/login/
WARNING 2025-06-24 23:00:23,884 basehttp 46400 59216 "GET /accounts/login/?next=/mailing/recipients/ HTTP/1.1" 404 2397
INFO 2025-06-24 23:00:28,973 basehttp 46400 59216 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-06-24 23:00:29,000 basehttp 46400 59216 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4177
INFO 2025-06-24 23:00:32,882 basehttp 46400 59216 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4355
INFO 2025-06-24 23:00:46,986 basehttp 46400 59216 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4355
INFO 2025-06-24 23:00:57,912 basehttp 46400 59216 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-06-24 23:00:58,068 basehttp 46400 59216 "GET /admin/ HTTP/1.1" 200 7260
INFO 2025-06-24 23:01:01,517 basehttp 46400 59216 "GET /admin/auth/group/ HTTP/1.1" 200 8701
INFO 2025-06-24 23:01:01,591 basehttp 46400 59216 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-06-24 23:01:02,548 basehttp 46400 59216 "GET /admin/ HTTP/1.1" 200 7260
INFO 2025-06-24 23:01:03,229 basehttp 46400 59216 "GET /admin/auth/user/ HTTP/1.1" 200 12280
INFO 2025-06-24 23:01:03,298 basehttp 46400 59216 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-06-24 23:01:05,179 basehttp 46400 59216 "GET /admin/ HTTP/1.1" 200 7260
INFO 2025-06-24 23:01:05,970 basehttp 46400 59216 "GET /admin/mailing/mailingrecipient/ HTTP/1.1" 200 9682
INFO 2025-06-24 23:01:06,035 basehttp 46400 59216 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-06-24 23:01:06,877 basehttp 46400 59216 "GET /admin/ HTTP/1.1" 200 7260
WARNING 2025-06-24 23:01:11,151 log 46400 59216 Not Found: /
WARNING 2025-06-24 23:01:11,151 basehttp 46400 59216 "GET / HTTP/1.1" 404 2308
WARNING 2025-06-24 23:01:16,453 log 46400 59216 Not Found: /mailing/
WARNING 2025-06-24 23:01:16,454 basehttp 46400 59216 "GET /mailing/ HTTP/1.1" 404 7300
INFO 2025-06-24 23:01:21,233 basehttp 46400 59216 "GET /mailing/recipients/ HTTP/1.1" 200 3081
INFO 2025-06-24 23:01:23,719 basehttp 46400 59216 "GET /mailing/recipients/create/ HTTP/1.1" 200 5028
INFO 2025-06-24 23:01:25,833 basehttp 46400 59216 "GET /mailing/recipients/ HTTP/1.1" 200 3081
INFO 2025-06-24 23:01:27,030 basehttp 46400 59216 "GET /mailing/messages/ HTTP/1.1" 200 3062
INFO 2025-06-24 23:01:28,065 basehttp 46400 59216 "GET /mailing/mailings/ HTTP/1.1" 200 3735
WARNING 2025-06-24 23:01:29,817 log 46400 59216 Method Not Allowed (POST): /mailing/mailings/
WARNING 2025-06-24 23:01:29,817 basehttp 46400 59216 "POST /mailing/mailings/ HTTP/1.1" 405 0
INFO 2025-06-24 23:01:32,291 basehttp 46400 59216 "GET /mailing/home/ HTTP/1.1" 200 4392
INFO 2025-06-24 23:01:33,731 basehttp 46400 59216 "GET /mailing/mailing-attempts/ HTTP/1.1" 200 4463
INFO 2025-06-24 23:01:39,827 basehttp 46400 59216 "GET /mailing/mailings/create/ HTTP/1.1" 200 5316
INFO 2025-06-24 23:01:55,404 basehttp 46400 59216 "GET /mailing/home/ HTTP/1.1" 200 4392
INFO 2025-06-24 23:01:55,885 basehttp 46400 59216 "GET /mailing/recipients/ HTTP/1.1" 200 3081
INFO 2025-06-24 23:01:57,049 basehttp 46400 59216 "GET /mailing/recipients/create/ HTTP/1.1" 200 5028
INFO 2025-06-24 23:02:17,110 basehttp 46400 59216 "POST /mailing/recipients/create/ HTTP/1.1" 302 0
INFO 2025-06-24 23:02:17,159 basehttp 46400 59216 "GET /mailing/recipients/ HTTP/1.1" 200 4029
INFO 2025-06-24 23:02:19,399 basehttp 46400 59216 "GET /mailing/recipients/1/update/ HTTP/1.1" 200 5088
INFO 2025-06-24 23:02:21,413 basehttp 46400 59216 "GET /mailing/recipients/create/ HTTP/1.1" 200 5028
INFO 2025-06-24 23:02:37,253 basehttp 46400 59216 "POST /mailing/recipients/create/ HTTP/1.1" 302 0
INFO 2025-06-24 23:02:37,409 basehttp 46400 59216 "GET /mailing/recipients/ HTTP/1.1" 200 4978
INFO 2025-06-24 23:02:38,597 basehttp 46400 59216 "GET /mailing/recipients/create/ HTTP/1.1" 200 5028
INFO 2025-06-24 23:03:01,119 basehttp 46400 59216 "POST /mailing/recipients/create/ HTTP/1.1" 302 0
INFO 2025-06-24 23:03:01,169 basehttp 46400 59216 "GET /mailing/recipients/ HTTP/1.1" 200 5922
INFO 2025-06-24 23:03:02,759 basehttp 46400 59216 "GET /mailing/messages/ HTTP/1.1" 200 3062
INFO 2025-06-24 23:03:04,002 basehttp 46400 59216 "GET /mailing/messages/create/ HTTP/1.1" 200 4649
INFO 2025-06-24 23:03:24,947 basehttp 46400 59216 "POST /mailing/messages/create/ HTTP/1.1" 302 0
INFO 2025-06-24 23:03:25,100 basehttp 46400 59216 "GET /mailing/messages/ HTTP/1.1" 200 4136
INFO 2025-06-24 23:03:28,103 basehttp 46400 59216 "GET /mailing/messages/create/ HTTP/1.1" 200 4649
INFO 2025-06-24 23:03:40,861 basehttp 46400 59216 "POST /mailing/messages/create/ HTTP/1.1" 302 0
INFO 2025-06-24 23:03:40,912 basehttp 46400 59216 "GET /mailing/messages/ HTTP/1.1" 200 5158
INFO 2025-06-24 23:03:41,928 basehttp 46400 59216 "GET /mailing/messages/create/ HTTP/1.1" 200 4649
INFO 2025-06-24 23:03:52,755 basehttp 46400 59216 "POST /mailing/messages/create/ HTTP/1.1" 302 0
INFO 2025-06-24 23:03:52,803 basehttp 46400 59216 "GET /mailing/messages/ HTTP/1.1" 200 6163
INFO 2025-06-24 23:03:55,610 basehttp 46400 59216 "GET /mailing/mailings/ HTTP/1.1" 200 3735
INFO 2025-06-24 23:03:56,430 basehttp 46400 59216 "GET /mailing/mailings/create/ HTTP/1.1" 200 6197
INFO 2025-06-24 23:04:08,518 basehttp 46400 59216 "GET /mailing/mailings/create/ HTTP/1.1" 200 6197
INFO 2025-06-24 23:05:55,212 autoreload 46400 62268 D:\python\django_course\mailing\forms.py changed, reloading.
INFO 2025-06-24 23:05:55,634 autoreload 60312 62872 Watching for file changes with StatReloader
INFO 2025-06-24 23:06:39,461 autoreload 60312 62872 D:\python\django_course\mailing\urls.py changed, reloading.
INFO 2025-06-24 23:06:39,870 autoreload 59260 45772 Watching for file changes with StatReloader
INFO 2025-06-24 23:08:11,887 basehttp 59260 64100 "GET /mailing/mailings/create/ HTTP/1.1" 200 7154
INFO 2025-06-24 23:08:36,674 basehttp 59260 64100 "POST /mailing/mailings/create/ HTTP/1.1" 302 0
INFO 2025-06-24 23:08:36,725 basehttp 59260 64100 "GET /mailing/mailings/ HTTP/1.1" 200 5017
INFO 2025-06-24 23:09:12,136 basehttp 59260 64100 "GET /mailing/mailings/ HTTP/1.1" 200 5017
INFO 2025-06-24 23:09:15,594 services 59260 64100 Письмо успешно отправлено для bonfiglioli@yandex.ru (рассылка ID: 1)
INFO 2025-06-24 23:09:15,595 services 59260 64100 Рассылка ID: 1 завершена по расписанию.
INFO 2025-06-24 23:09:15,596 basehttp 59260 64100 "GET /mailing/mailing/1/run/ HTTP/1.1" 302 0
INFO 2025-06-24 23:09:15,651 basehttp 59260 64100 "GET /mailing/mailings/ HTTP/1.1" 200 5019
INFO 2025-06-24 23:12:18,679 autoreload 59260 45772 D:\python\django_course\mailing\views.py changed, reloading.
INFO 2025-06-24 23:12:19,122 autoreload 60756 63636 Watching for file changes with StatReloader
INFO 2025-06-24 23:12:26,407 autoreload 60756 63636 D:\python\django_course\mailing\views.py changed, reloading.
INFO 2025-06-24 23:12:26,862 autoreload 63892 61820 Watching for file changes with StatReloader
INFO 2025-06-24 23:12:59,462 autoreload 63892 61820 D:\python\django_course\mailing\urls.py changed, reloading.
INFO 2025-06-24 23:12:59,855 autoreload 52852 2288 Watching for file changes with StatReloader
INFO 2025-06-24 23:13:55,535 basehttp 52852 54852 "GET /mailing/mailings/ HTTP/1.1" 200 5096
INFO 2025-06-24 23:13:59,075 basehttp 52852 54852 "GET /mailing/toggle_activity/1/ HTTP/1.1" 302 0
INFO 2025-06-24 23:13:59,131 basehttp 52852 54852 "GET /mailing/mailings/ HTTP/1.1" 200 5106
INFO 2025-06-24 23:14:00,850 basehttp 52852 54852 "GET /mailing/toggle_activity/1/ HTTP/1.1" 302 0
INFO 2025-06-24 23:14:00,900 basehttp 52852 54852 "GET /mailing/mailings/ HTTP/1.1" 200 5096
INFO 2025-06-24 23:14:05,253 basehttp 52852 54852 "GET /mailing/toggle_activity/1/ HTTP/1.1" 302 0
INFO 2025-06-24 23:14:05,305 basehttp 52852 54852 "GET /mailing/mailings/ HTTP/1.1" 200 5106
INFO 2025-06-24 23:14:06,892 services 52852 54852 Письмо успешно отправлено для bonfiglioli@yandex.ru (рассылка ID: 1)
INFO 2025-06-24 23:14:06,893 services 52852 54852 Рассылка ID: 1 завершена по расписанию.
INFO 2025-06-24 23:14:06,894 basehttp 52852 54852 "GET /mailing/mailing/1/run/ HTTP/1.1" 302 0
INFO 2025-06-24 23:14:06,943 basehttp 52852 54852 "GET /mailing/mailings/ HTTP/1.1" 200 5106
INFO 2025-06-24 23:14:13,617 basehttp 52852 54852 "GET /mailing/toggle_activity/1/ HTTP/1.1" 302 0
INFO 2025-06-24 23:14:13,776 basehttp 52852 54852 "GET /mailing/mailings/ HTTP/1.1" 200 5096
INFO 2025-06-24 23:14:20,256 basehttp 52852 54852 "GET /mailing/toggle_activity/1/ HTTP/1.1" 302 0
INFO 2025-06-24 23:14:20,308 basehttp 52852 54852 "GET /mailing/mailings/ HTTP/1.1" 200 5106
INFO 2025-06-24 23:16:12,746 autoreload 52852 2288 D:\python\django_course\mailing\services.py changed, reloading.
INFO 2025-06-24 23:16:13,167 autoreload 52424 60312 Watching for file changes with StatReloader
INFO 2025-06-24 23:17:26,160 autoreload 52424 60312 D:\python\django_course\mailing\services.py changed, reloading.
INFO 2025-06-24 23:17:26,561 autoreload 53308 54776 Watching for file changes with StatReloader
INFO 2025-06-24 23:17:29,689 basehttp 53308 54060 "GET /mailing/mailings/ HTTP/1.1" 200 5160
INFO 2025-06-24 23:17:34,703 basehttp 53308 54060 "GET /mailing/toggle_activity/1/ HTTP/1.1" 302 0
INFO 2025-06-24 23:17:34,754 basehttp 53308 54060 "GET /mailing/mailings/ HTTP/1.1" 200 5161
INFO 2025-06-24 23:17:36,962 basehttp 53308 54060 "GET /mailing/toggle_activity/1/ HTTP/1.1" 302 0
INFO 2025-06-24 23:17:37,014 basehttp 53308 54060 "GET /mailing/mailings/ HTTP/1.1" 200 5160
INFO 2025-06-24 23:17:40,608 basehttp 53308 54060 "GET /mailing/toggle_activity/1/ HTTP/1.1" 302 0
INFO 2025-06-24 23:17:40,662 basehttp 53308 54060 "GET /mailing/mailings/ HTTP/1.1" 200 5161
INFO 2025-06-24 23:17:49,283 services 53308 54060 Рассылка ID: 1 запущена вручную пользователем admin.
INFO 2025-06-24 23:17:49,746 services 53308 54060 Письмо успешно отправлено для bonfiglioli@yandex.ru (рассылка ID: 1)
INFO 2025-06-24 23:17:49,747 services 53308 54060 Рассылка ID: 1 завершена после ручного запуска. Успешно: 1, Ошибок: 0.
INFO 2025-06-24 23:17:49,748 basehttp 53308 54060 "GET /mailing/mailing/1/run/ HTTP/1.1" 302 0
INFO 2025-06-24 23:17:49,800 basehttp 53308 54060 "GET /mailing/mailings/ HTTP/1.1" 200 5161
INFO 2025-06-24 23:18:12,883 basehttp 53308 54060 "GET /mailing/home/ HTTP/1.1" 200 4392
INFO 2025-06-24 23:18:15,625 basehttp 53308 54060 "GET /mailing/mailings/ HTTP/1.1" 200 5161
INFO 2025-06-24 23:18:18,478 basehttp 53308 54060 "GET /mailing/mailings/ HTTP/1.1" 200 5161
INFO 2025-06-24 23:20:18,254 autoreload 53308 54776 D:\python\django_course\mailing\views.py changed, reloading.
INFO 2025-06-24 23:20:18,641 autoreload 59508 64440 Watching for file changes with StatReloader
INFO 2025-06-24 23:20:49,776 basehttp 59508 18492 "GET /mailing/home/ HTTP/1.1" 200 4348
INFO 2025-06-24 23:20:52,777 basehttp 59508 18492 "GET /mailing/mailings/ HTTP/1.1" 200 5161
INFO 2025-06-24 23:20:54,498 basehttp 59508 18492 "GET /mailing/toggle_activity/1/ HTTP/1.1" 302 0
INFO 2025-06-24 23:20:54,551 basehttp 59508 18492 "GET /mailing/mailings/ HTTP/1.1" 200 5160
INFO 2025-06-24 23:20:55,791 basehttp 59508 18492 "GET /mailing/toggle_activity/1/ HTTP/1.1" 302 0
INFO 2025-06-24 23:20:55,951 basehttp 59508 18492 "GET /mailing/mailings/ HTTP/1.1" 200 5161
INFO 2025-06-24 23:20:57,640 basehttp 59508 18492 "GET /mailing/home/ HTTP/1.1" 200 4348
INFO 2025-06-24 23:20:58,758 basehttp 59508 18492 "GET /mailing/recipients/ HTTP/1.1" 200 5922
INFO 2025-06-24 23:22:41,886 autoreload 59508 64440 D:\python\django_course\mailing\views.py changed, reloading.
INFO 2025-06-24 23:22:42,313 autoreload 62256 55148 Watching for file changes with StatReloader
INFO 2025-06-24 23:22:43,835 basehttp 62256 64068 "GET /mailing/recipients/ HTTP/1.1" 200 5922
INFO 2025-06-24 23:22:45,067 basehttp 62256 64068 "GET /mailing/home/ HTTP/1.1" 200 4350
INFO 2025-06-24 23:23:47,876 basehttp 62256 64068 "GET /mailing/recipients/ HTTP/1.1" 200 5922
INFO 2025-06-24 23:23:49,299 basehttp 62256 64068 "GET /mailing/messages/ HTTP/1.1" 200 6163
INFO 2025-06-24 23:23:50,280 basehttp 62256 64068 "GET /mailing/mailings/ HTTP/1.1" 200 5161
INFO 2025-06-24 23:23:53,078 basehttp 62256 64068 "GET /mailing/home/ HTTP/1.1" 200 4350
INFO 2025-06-24 23:23:57,965 basehttp 62256 64068 "GET /mailing/mailing-attempts/ HTTP/1.1" 200 6128
INFO 2025-06-24 23:24:03,284 basehttp 62256 64068 "GET /mailing/mailings/create/ HTTP/1.1" 200 7154
INFO 2025-06-25 01:01:30,728 autoreload 57356 63004 Watching for file changes with StatReloader
WARNING 2025-06-25 01:01:31,889 log 57356 64880 Not Found: /
WARNING 2025-06-25 01:01:31,889 basehttp 57356 64880 "GET / HTTP/1.1" 404 2457
WARNING 2025-06-25 01:01:38,484 log 57356 64880 Not Found: /users/
WARNING 2025-06-25 01:01:38,485 basehttp 57356 64880 "GET /users/ HTTP/1.1" 404 3441
INFO 2025-06-25 01:01:42,814 basehttp 57356 64880 "GET /users/register/ HTTP/1.1" 200 5799
INFO 2025-06-25 01:01:56,939 basehttp 57356 64880 "POST /users/register/ HTTP/1.1" 200 6171
ERROR 2025-06-25 01:01:58,467 log 57356 64880 Internal Server Error: /mailing/home/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2128, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\views\generic\base.py", line 228, in get
    context = self.get_context_data(**kwargs)
  File "D:\python\django_course\mailing\views.py", line 230, in get_context_data
    all_mailings = Mailing.objects.filter(owner=self.request.user)
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1415, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ~~~~~~~~~~~~~~~~~~~~^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2130, in get_prep_value
    raise e.__class__(
        "Field '%s' expected a number but got %r." % (self.name, value),
    ) from e
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x0000029373067230>>.
ERROR 2025-06-25 01:01:58,472 basehttp 57356 64880 "GET /mailing/home/ HTTP/1.1" 500 141932
INFO 2025-06-25 01:02:08,030 basehttp 57356 64880 "GET /users/register/ HTTP/1.1" 200 4874
INFO 2025-06-25 01:02:09,159 basehttp 57356 64880 "GET /mailing/recipients/ HTTP/1.1" 302 0
ERROR 2025-06-25 01:02:09,178 log 57356 64880 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-06-25 01:02:09,179 basehttp 57356 64880 "GET /users/login/?next=/mailing/recipients/ HTTP/1.1" 500 82553
INFO 2025-06-25 01:02:12,819 basehttp 57356 64880 "GET /mailing/messages/ HTTP/1.1" 302 0
ERROR 2025-06-25 01:02:12,838 log 57356 64880 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-06-25 01:02:12,840 basehttp 57356 64880 "GET /users/login/?next=/mailing/messages/ HTTP/1.1" 500 82541
INFO 2025-06-25 01:02:14,503 basehttp 57356 64880 "GET /mailing/mailings/ HTTP/1.1" 302 0
ERROR 2025-06-25 01:02:14,518 log 57356 64880 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-06-25 01:02:14,519 basehttp 57356 64880 "GET /users/login/?next=/mailing/mailings/ HTTP/1.1" 500 82541
INFO 2025-06-25 01:02:30,662 basehttp 57356 64880 "POST /users/register/ HTTP/1.1" 200 6171
ERROR 2025-06-25 01:03:27,177 log 57356 64880 Internal Server Error: /mailing/home/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2128, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\views\generic\base.py", line 228, in get
    context = self.get_context_data(**kwargs)
  File "D:\python\django_course\mailing\views.py", line 230, in get_context_data
    all_mailings = Mailing.objects.filter(owner=self.request.user)
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1415, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ~~~~~~~~~~~~~~~~~~~~^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2130, in get_prep_value
    raise e.__class__(
        "Field '%s' expected a number but got %r." % (self.name, value),
    ) from e
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000293730A3CE0>>.
ERROR 2025-06-25 01:03:27,180 basehttp 57356 64880 "GET /mailing/home/ HTTP/1.1" 500 141783
INFO 2025-06-25 01:06:24,454 autoreload 57356 63004 D:\python\django_course\mailing\views.py changed, reloading.
INFO 2025-06-25 01:06:24,863 autoreload 59984 63768 Watching for file changes with StatReloader
INFO 2025-06-25 01:06:26,156 basehttp 59984 62324 "GET /mailing/home/ HTTP/1.1" 302 0
ERROR 2025-06-25 01:06:26,185 log 59984 62324 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-06-25 01:06:26,187 basehttp 59984 62324 "GET /users/login/?next=/mailing/home/ HTTP/1.1" 500 82654
INFO 2025-06-25 01:06:30,245 basehttp 59984 62324 "GET /mailing/home/ HTTP/1.1" 302 0
ERROR 2025-06-25 01:06:30,260 log 59984 62324 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-06-25 01:06:30,261 basehttp 59984 62324 "GET /users/login/?next=/mailing/home/ HTTP/1.1" 500 82517
INFO 2025-06-25 01:06:32,677 basehttp 59984 62324 "GET /mailing/home/ HTTP/1.1" 302 0
ERROR 2025-06-25 01:06:32,693 log 59984 62324 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-06-25 01:06:32,695 basehttp 59984 62324 "GET /users/login/?next=/mailing/home/ HTTP/1.1" 500 82517
INFO 2025-06-25 01:06:38,844 basehttp 59984 62324 "GET /mailing/recipients/ HTTP/1.1" 302 0
ERROR 2025-06-25 01:06:38,858 log 59984 62324 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-06-25 01:06:38,859 basehttp 59984 62324 "GET /users/login/?next=/mailing/recipients/ HTTP/1.1" 500 82553
INFO 2025-06-25 01:06:40,156 basehttp 59984 62324 "GET /mailing/messages/ HTTP/1.1" 302 0
ERROR 2025-06-25 01:06:40,172 log 59984 62324 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-06-25 01:06:40,173 basehttp 59984 62324 "GET /users/login/?next=/mailing/messages/ HTTP/1.1" 500 82541
INFO 2025-06-25 01:08:50,091 autoreload 59984 63768 D:\python\django_course\mailing\views.py changed, reloading.
INFO 2025-06-25 01:08:50,517 autoreload 58792 42856 Watching for file changes with StatReloader
INFO 2025-06-25 01:09:10,987 basehttp 58792 66480 "POST /users/register/ HTTP/1.1" 200 5685
INFO 2025-06-25 01:09:12,297 basehttp 58792 66480 "GET /mailing/home/ HTTP/1.1" 200 3864
ERROR 2025-06-25 01:09:14,992 log 58792 66480 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-06-25 01:09:14,994 basehttp 58792 66480 "GET /users/login/ HTTP/1.1" 500 82093
INFO 2025-06-25 01:09:29,252 basehttp 58792 66480 "GET /users/register/ HTTP/1.1" 200 4388
ERROR 2025-06-25 01:09:30,568 log 58792 66480 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-06-25 01:09:30,570 basehttp 58792 66480 "GET /users/login/ HTTP/1.1" 500 82095
ERROR 2025-06-25 01:10:34,989 log 58792 66480 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-06-25 01:10:34,990 basehttp 58792 66480 "GET /users/login/ HTTP/1.1" 500 82095
ERROR 2025-06-25 01:12:27,588 log 58792 66480 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2025-06-25 01:12:27,592 basehttp 58792 66480 "GET /users/login/ HTTP/1.1" 500 154085
ERROR 2025-06-25 01:12:58,850 log 58792 66480 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'registration/login' not found. 'registration/login' is not a valid view function or pattern name.
ERROR 2025-06-25 01:12:58,852 basehttp 58792 66480 "GET /users/login/ HTTP/1.1" 500 154423
ERROR 2025-06-25 01:13:17,246 log 58792 66480 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'registration/login' not found. 'registration/login' is not a valid view function or pattern name.
ERROR 2025-06-25 01:13:17,249 basehttp 58792 66480 "GET /users/login/ HTTP/1.1" 500 154954
ERROR 2025-06-25 01:13:33,792 log 58792 66480 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-06-25 01:13:33,793 basehttp 58792 66480 "GET /users/login/ HTTP/1.1" 500 82232
INFO 2025-06-25 01:14:30,518 autoreload 58792 42856 D:\python\django_course\users\urls.py changed, reloading.
INFO 2025-06-25 01:14:30,940 autoreload 57068 39684 Watching for file changes with StatReloader
ERROR 2025-06-25 01:14:31,986 log 57068 45748 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
ERROR 2025-06-25 01:14:31,988 basehttp 57068 45748 "GET /users/login/ HTTP/1.1" 500 82024
INFO 2025-06-25 01:14:38,249 autoreload 57068 39684 D:\python\django_course\users\urls.py changed, reloading.
INFO 2025-06-25 01:14:38,663 autoreload 62472 64864 Watching for file changes with StatReloader
ERROR 2025-06-25 01:14:39,035 log 62472 60724 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: users:login.html
ERROR 2025-06-25 01:14:39,037 basehttp 62472 60724 "GET /users/login/ HTTP/1.1" 500 82120
INFO 2025-06-25 01:14:43,925 autoreload 62472 64864 D:\python\django_course\users\urls.py changed, reloading.
INFO 2025-06-25 01:14:44,364 autoreload 58100 66168 Watching for file changes with StatReloader
ERROR 2025-06-25 01:14:45,042 log 58100 54096 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2025-06-25 01:14:45,046 basehttp 58100 54096 "GET /users/login/ HTTP/1.1" 500 154071
INFO 2025-06-25 01:15:05,833 autoreload 58100 66168 D:\python\django_course\users\urls.py changed, reloading.
INFO 2025-06-25 01:15:06,236 autoreload 59284 67044 Watching for file changes with StatReloader
INFO 2025-06-25 01:15:20,612 autoreload 59284 67044 D:\python\django_course\users\urls.py changed, reloading.
INFO 2025-06-25 01:15:21,004 autoreload 54576 52532 Watching for file changes with StatReloader
INFO 2025-06-25 01:19:38,622 autoreload 54576 52532 D:\python\django_course\users\urls.py changed, reloading.
INFO 2025-06-25 01:19:39,061 autoreload 62524 65236 Watching for file changes with StatReloader
INFO 2025-06-25 01:19:51,316 autoreload 62524 65236 D:\python\django_course\users\urls.py changed, reloading.
INFO 2025-06-25 01:19:51,743 autoreload 50804 58376 Watching for file changes with StatReloader
ERROR 2025-06-25 01:19:52,446 log 50804 19040 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2025-06-25 01:19:52,450 basehttp 50804 19040 "GET /users/login/ HTTP/1.1" 500 154071
ERROR 2025-06-25 01:19:53,640 log 50804 19040 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2025-06-25 01:19:53,642 basehttp 50804 19040 "GET /users/login/ HTTP/1.1" 500 154071
ERROR 2025-06-25 01:20:15,105 log 50804 19040 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'users/login' not found. 'users/login' is not a valid view function or pattern name.
ERROR 2025-06-25 01:20:15,108 basehttp 50804 19040 "GET /users/login/ HTTP/1.1" 500 153991
ERROR 2025-06-25 01:20:20,051 log 50804 19040 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\django_course\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\django_course\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\python\django_course\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset' not found. 'password_reset' is not a valid view function or pattern name.
ERROR 2025-06-25 01:20:20,054 basehttp 50804 19040 "GET /users/login/ HTTP/1.1" 500 152807
INFO 2025-06-25 01:20:28,180 basehttp 50804 19040 "GET /users/login/ HTTP/1.1" 200 3638
INFO 2025-06-25 01:20:32,947 basehttp 50804 19040 "GET /users/register/ HTTP/1.1" 200 4377
INFO 2025-06-25 01:20:33,848 basehttp 50804 19040 "GET /users/login/ HTTP/1.1" 200 3638
INFO 2025-06-25 01:22:03,753 autoreload 50804 58376 D:\python\django_course\users\forms.py changed, reloading.
INFO 2025-06-25 01:22:04,156 autoreload 64316 53528 Watching for file changes with StatReloader
INFO 2025-06-25 01:25:23,000 autoreload 64316 53528 D:\python\django_course\users\urls.py changed, reloading.
INFO 2025-06-25 01:25:23,419 autoreload 47992 66232 Watching for file changes with StatReloader
INFO 2025-06-25 01:25:29,603 autoreload 47992 66232 D:\python\django_course\users\urls.py changed, reloading.
INFO 2025-06-25 01:25:29,984 autoreload 16328 59088 Watching for file changes with StatReloader
INFO 2025-06-25 01:25:31,693 basehttp 16328 56840 "GET /users/login/ HTTP/1.1" 200 3741
INFO 2025-06-25 01:32:48,954 basehttp 16328 65748 "GET /mailing/home/ HTTP/1.1" 200 3853
INFO 2025-06-25 01:32:50,479 basehttp 16328 65748 "GET /users/login/ HTTP/1.1" 200 3741
INFO 2025-06-25 01:32:51,237 basehttp 16328 65748 "GET /users/register/ HTTP/1.1" 200 4377
